version: '3'
services:
  web:
    build: .
    restart: always
    # container_name: tomcat
    ports:
      - 8080:8080 
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    environment:
      - TZ= Asia/Shanghai
      - SPRING_PROFILES_ACTIVE=dev
  redis:
    image: "redis:alpine"

    



